name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for WIF
      contents: read   # Allows actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pulumi
        uses: pulumi/actions@v4

      # Authenticate to GCP via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Install Infra Dependencies
        run: |
          cd infra
          pip install -r requirements.txt

      - name: Deploy with Pulumi
        run: |
          cd infra
          pulumi stack init dev || true
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT }}
