name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for Workload Identity Federation
      contents: read   # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Install Infra Dependencies
        run: |
          cd infra
          pip install -r requirements.txt

      - name: Install dependencies
        run: pip install -r automation/requirements.txt

      - name: Deploy with Pulumi
        run: |
          cd infra
          pulumi stack init dev || true
          pulumi stack select dev 
          pulumi config set gcp:project ${{ vars.GCP_PROJECT }} --stack dev
          pulumi config set gcp:region us-central1 --stack dev
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CLOUD_PROJECT: ${{ vars.GCP_PROJECT }}
